require_relative "next_number.rb"
require_relative "previous_number.rb"
require_relative "square.rb"
require_relative "cube.rb"

require_relative "is_negative.rb"
require_relative "is_even.rb"
require_relative "is_odd.rb"
require_relative "absolute.rb"
require_relative "between.rb"
require_relative "between_strict.rb"
require_relative "min_of_two.rb"
require_relative "min_of_three.rb"
require_relative "min_of_four.rb"
require_relative "max_of_two.rb"
require_relative "max_of_three.rb"
require_relative "max_of_four.rb"