require_relative "next_number.rb"
require_relative "previous_number.rb"
require_relative "square.rb"
require_relative "cube.rb"

require_relative "is_negative.rb"
require_relative "is_even.rb"
require_relative "is_odd.rb"
require_relative "absolute.rb"
require_relative "between.rb"